<a href="https://colab.research.google.com/github/SterlingHayden/Pyomo-Introduction/blob/main/CheckingGaussJordan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checking Gauss-Jordan Elimination using a Matrix Inverse

In [ ]:
import numpy as np
from numpy import linalg as LA

## Example 3 from Linear Algebra Primer I

\begin{equation*}
[A|b] = \left[\begin{array}{rrr}
1 & 2 & 1 \\
1 & -1 & 2 \\
3 & 0 & 1
 \end{array} \left| \begin{array}{r} 13 \\ 13 \\ 5\end{array} \right. \right]
\end{equation*}

In [ ]:
A = np.array([[1, 2, 1],[1, -1, 2], [3, 0, 1]])
b = np.array([[13], [13], [15]])
print(A)
print(b)

[[ 1  2  1]
 [ 1 -1  2]
 [ 3  0  1]]
[[13]
 [13]
 [15]]


Because $A$ is an invertible square matrix, $x = A^{-1}b$.

In [ ]:
x = LA.inv(A) @ b
print(x)

x = LA.solve(A,b)
print(x)

[[3.]
 [2.]
 [6.]]
[[3.]
 [2.]
 [6.]]


## Example 8 from Linear Algebra Primer I

\begin{equation*}
[A|b] = \left[\begin{array}{rrrrr}
1 & 1 & -2 & 2 & -1\\
2 & 4 & -1 & 8 & 1
\end{array} \left| \begin{array}{r} 3 \\ 19 \end{array} \right. \right]
\end{equation*}

In [ ]:
A = np.array([[1, 1, -2, 2, -1],[2, 4, -1, 8, 1]])
b = np.array([[3], [19]])

print(A)
print(b)

[[ 1  1 -2  2 -1]
 [ 2  4 -1  8  1]]
[[ 3]
 [19]]


We want to solve for $x_4$ and $x_5$ in terms of the remaining variables; therefore construct a basis matrix $B$ by extracting the $x_4$ and $x_5$ columns of $A$.

In [ ]:
B = A[:,[3,4]]
B


array([[ 2, -1],
       [ 8,  1]])

If it is possible to solve for $x_4$ and $x_5$ in terms of the remaining variables, $B$ will be invertible and the system resulting from Gauss-Jordan elimination will be $B^{-1}Ax = B^{-1}b$

In [ ]:
Abar = LA.inv(B) @ A
bbar = LA.inv(B) @ b
print(Abar)
print(bbar)

[[ 0.3  0.5 -0.3  1.   0. ]
 [-0.4  0.   1.4  0.   1. ]]
[[2.2]
 [1.4]]
